# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
   main.show-banner: false
   h2:
      console:
         enabled: true
   datasource:
      url: jdbc:h2:~/test
      username: system
      password: 
      driverClassName: org.h2.Driver

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

ORDER_ITEMS_HOST_URL: http://localhost:8080/orderitem
