# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

server:
  port: 8082

spring:
   main.show-banner: false
   h2:
      console:
         enabled: true
   datasource:
      url: jdbc:h2:file:~/build/data/oms-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
      username: sa
      password: password
      driverClassName: org.h2.Driver

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true

api-client:
  host: http://localhost:8081
  order-items-endpoint: /orderitem